#!/usr/bin/env bash

echo "creating bucket"

# Check if the first argument is provided (bucket name)
if [ -z "$1" ]; then
  echo "No bucket name provided. (s3://my-bucket)"
  exit 1
fi

BUCKET_NAME=$1

aws s3api create-bucket \
--bucket $BUCKET_NAME \
--query Location \
--output text