#!/usr/bin/env bash

# Exit immediately if any command exits with a non-zero status
set -e

# Check if the first argument is provided (bucket name)
if [ -z "$1" ]; then
  echo "No bucket name provided. (s3://my-bucket)"
  exit 1
fi

BUCKET_NAME=$1

aws s3api delete-bucket \
--bucket $BUCKET_NAME

echo "bucket $BUCKET_NAME deleted"