#!/usr/bin/env bash

export AWS_PAGER=""

echo "listing objects"

# Check for bucket name
if [ -z "$1" ]; then
  echo "No bucket name provided. (s3://my-bucket)"
  exit 1
fi

BUCKET_NAME=$1

aws s3api list-objects-v2 \
    --bucket $BUCKET_NAME