#!/usr/bin/env bash
echo "uploading to bucket"

# Check for bucket name
if [ -z "$1" ]; then
  echo "No bucket name provided. (s3://my-bucket)"
  exit 1
fi

# Check for filename prefix
if [ -z "$2" ]; then
  echo "No filename provided"
  exit 1
fi

BUCKET_NAME=$1
FILENAME=$2
OBJECT_KEY=$(basename "$FILENAME")

aws s3api put-object \
    --bucket $BUCKET_NAME \
    --body $FILENAME \
    --key $OBJECT_KEY