#!/usr/bin/env bash

echo "== sync"

# Check for bucket name
if [ -z "$1" ]; then
  echo "No bucket name provided. (s3://my-bucket)"
  exit 1
fi

# Check for filename prefix
if [ -z "$2" ]; then
  echo "No filename prefix provided. (s3://my-bucket)"
  exit 1
fi

BUCKET_NAME=$1
FILENAME_PREFIX=$2

# where we'll store the files
OUTPUT_DIR="/tmp/s3-bash-scripts"

# remove folder if it already exists
rm -r $OUTPUT_DIR

# create output folder
mkdir -p "$OUTPUT_DIR"

# Generate a random number to determine number of files to be created
num_files=$((RANDOM % 6 + 5))

echo "Creating $num_files random files"

for ((i=1; i<=$num_files; i++)); do
    # Generate a random filename
    filename="$OUTPUT_DIR/${FILENAME_PREFIX}_$i.txt"

    # Generate random data and wirte it to the file
    dd if=/dev/urandom of="$filename" bs=1024 count=$((RANDOM % 1024 +1)) 2>/dev/null
done

tree $OUTPUT_DIR

aws s3 sync $OUTPUT_DIR s3://$BUCKET_NAME/files