AWSTemplateFormatVersion: "2010-09-09"
Description: a simple s3 bucket
Resources:
  S3Bucket:
    Type: 'AWS::S3::Bucket'
    DeletionPolicy: Retain
    Properties:
      BucketName: DOC-EXAMPLE-BUCKET